### ISSUE TITLE
CrossLink doesn't send the message to the interface/unfiltered channel

### ISSUE THREAD

**Issue by IpProxyNeon** [IpProxyNeon/Community-discord-bot#7]
There's no error in the console, so I really am clueless on how to fix it...

**Comment by Jekabs123** [comment]
Try this:
`try:
    page = urllib.request.urlopen('https://raw.githubusercontent.com/Jekabs123/discord-bot/master/files/crosslink/allowedUsers.json')
    f = open("allowedUsers.json", "w")
    value = str(page.read()).replace(str(chr(92))+"n'", '')
    value = value.replace("b'", '')
    print(value)
    f.write(value)
    f.close()
except Exception as e:
    print(e)

#Some other code

        if message.channel.id == 637949482784260124 and message.author.id != self.client.user.id:
            f=open('allowedUsers.json','r+')
            crsLnkBots = json.load(f)
            f.close()
            if message.author.id in crsLnkBots:
                for channel in CIDs:
                    if not message.channel.id == channel:
                        await self.client.get_channel(int(channel)).send(msg)
            else:
                await message.channel.send("You are not registered in the cross-link network. To register please message AUser0#1791")`

**Comment by IpProxyNeon** [comment]
Anyone is supposed to be able to add or remove a link though

**Comment by IpProxyNeon** [comment]
Also, I want to be able to use the current code, but just modify it a little bit so it will send it to the unfiltered channel

**Comment by Xevion** [comment]
I honestly have no idea what large portions of the code is doing, I just write around it, not correcting it, hoping that it works the same way because I have no idea of what the origin intentions were when writing it.

**Comment by IpProxyNeon** [comment]
Ok then, thanks anyway, I'ma see if I can correct the problem

**Comment by IpProxyNeon** [comment]
CrossLink no longer works at all...

**Comment by IpProxyNeon** [comment]
Now works again after Brit rewritten in Hata! (Thanks HuyaneMatsu!)
